base_images:
  base:
    name: "4.6"
    namespace: ocp
    tag: cli
build_root:
  image_stream_tag:
    name: "4.6"
    namespace: ocp
    tag: cli
images:
- dockerfile_path: Dockerfile.prow
  from: base
  inputs:
    base:
      as:
      - registry.ci.openshift.org/ocp/4.6:cli
  to: must-gather
promotion:
  name: "2.3"
  namespace: open-cluster-management
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
zz_generated_metadata:
  branch: main
  org: open-cluster-management
  repo: must-gather
